name: jg_group
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.1
  get_it: ^8.0.3
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  lucide_icons_flutter: ^2.0.3
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  video_player: ^2.9.5
  flutter_cache_manager: ^3.4.1
  preload_page_view: ^0.2.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true