// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAggGsQzKHZcydv-XdnPXjwMqhU4wbwPQg',
    appId: '1:895275218216:web:48b26c35396fd610d88c1d',
    messagingSenderId: '895275218216',
    projectId: 'videofeed-1bb74',
    authDomain: 'videofeed-1bb74.firebaseapp.com',
    databaseURL: 'https://videofeed-1bb74-default-rtdb.firebaseio.com',
    storageBucket: 'videofeed-1bb74.firebasestorage.app',
    measurementId: 'G-7SBE18VEW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp6_UGTIldlDF5FS20-kJA3Vkkt3Cm3tk',
    appId: '1:895275218216:android:7959523fb36c15e9d88c1d',
    messagingSenderId: '895275218216',
    projectId: 'videofeed-1bb74',
    databaseURL: 'https://videofeed-1bb74-default-rtdb.firebaseio.com',
    storageBucket: 'videofeed-1bb74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbB036wjJwtxgVc7ZVX18f8bnMHQVnRIE',
    appId: '1:895275218216:ios:1f5ac46357e5be94d88c1d',
    messagingSenderId: '895275218216',
    projectId: 'videofeed-1bb74',
    databaseURL: 'https://videofeed-1bb74-default-rtdb.firebaseio.com',
    storageBucket: 'videofeed-1bb74.firebasestorage.app',
    iosClientId: '895275218216-avbh9kjsohrffo6ufhjcg680lftdprl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.jgGroup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbB036wjJwtxgVc7ZVX18f8bnMHQVnRIE',
    appId: '1:895275218216:ios:1f5ac46357e5be94d88c1d',
    messagingSenderId: '895275218216',
    projectId: 'videofeed-1bb74',
    databaseURL: 'https://videofeed-1bb74-default-rtdb.firebaseio.com',
    storageBucket: 'videofeed-1bb74.firebasestorage.app',
    iosClientId: '895275218216-avbh9kjsohrffo6ufhjcg680lftdprl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.jgGroup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAggGsQzKHZcydv-XdnPXjwMqhU4wbwPQg',
    appId: '1:895275218216:web:ac312b1c1ebcb5d3d88c1d',
    messagingSenderId: '895275218216',
    projectId: 'videofeed-1bb74',
    authDomain: 'videofeed-1bb74.firebaseapp.com',
    databaseURL: 'https://videofeed-1bb74-default-rtdb.firebaseio.com',
    storageBucket: 'videofeed-1bb74.firebasestorage.app',
    measurementId: 'G-BQXZBZC3CX',
  );
}
